# Generated by Django 4.0.3 on 2023-01-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('stock_is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('risk_to_reward_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stock', models.ForeignKey(limit_choices_to={'stock_is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='tradingstrategies.stock')),
            ],
        ),
    ]
