# Generated by Django 4.0.3 on 2023-01-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingstrategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='strategy_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
