# Generated by Django 4.0.3 on 2023-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingstrategies', '0002_strategy_strategy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='max_stop_loss',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
