# Generated by Django 4.0.3 on 2023-02-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingstrategies', '0003_strategy_max_stop_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='max_stop_loss',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='risk_to_reward_ratio',
            field=models.FloatField(),
        ),
    ]
