# Generated by Django 4.0.3 on 2023-01-14 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authTokens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthTokens',
            new_name='AuthToken',
        ),
    ]
