# Generated by Django 4.0.3 on 2023-01-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authTokens', '0002_rename_authtokens_authtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='access_token',
            new_name='api_access_token',
        ),
        migrations.RenameField(
            model_name='authtoken',
            old_name='refresh_token',
            new_name='api_refresh_token',
        ),
    ]
