# Generated by Django 4.0.3 on 2023-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authTokens', '0003_rename_access_token_authtoken_api_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='api_account_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtoken',
            name='api_consumer_key',
            field=models.CharField(default='ugigbi', max_length=1000),
            preserve_default=False,
        ),
    ]
