# Generated by Django 4.0.3 on 2023-01-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authTokens', '0004_authtoken_api_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='api_account_number',
            field=models.CharField(max_length=100),
        ),
    ]
