# Generated by Django 4.0.3 on 2023-02-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authTokens', '0005_alter_authtoken_api_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
